### PR TITLE
fix: add vertical scrolling to comments box

### LINKED ISSUE #12: Horizontal Scroll in the comments box
Need to add horizontal scroll for comments box

### PR DESCRIPTION
**Pull request by nafi-islam**
TODO:
- add horizontal scrolling to comments box

### CODE REVIEW

**Comment by skandrigi** [comment]
do you want me to merge?

**Comment by nafi-islam** [comment]
> do you want me to merge?

need to finish TODOs and look into the vertical text wrap

will try to finish today

**Comment by skandrigi** [comment]
👍

**Comment by nafi-islam** [comment]
@skandrigi 

[Screenshot 2024-11-13 at 10 41 22 AM](url)

code_editor makes the text static and enables horizontal scrolling

**Comment by skandrigi** [comment]
Tested from my computer, horizontal and vertical scrolling work. Merging

**Comment by jadenbanze** [comment]
Looks good to me. let's get it merged

**Pull request merged**
